//
// Created by pot on 06/09/18.
//

#ifndef PX4_CHARGING_I2C_H
#define PX4_CHARGING_I2C_H

/* MAX17205 Register adresses */
#define	NXTABLE0_REGISTER	 0x180   //nXTable0_REGISTER
#define	NXTABLE1_REGISTER	 0x181   //nXTable1_REGISTER
#define	NXTABLE2_REGISTER	 0x182   //nXTable2_REGISTER
#define	NXTABLE3_REGISTER	 0x183   //nXTable3_REGISTER
#define	NXTABLE4_REGISTER	 0x184   //nXTable4_REGISTER
#define	NXTABLE5_REGISTER	 0x185   //nXTable5_REGISTER
#define	NXTABLE6_REGISTER	 0x186   //nXTable6_REGISTER
#define	NXTABLE7_REGISTER	 0x187   //nXTable7_REGISTER
#define	NXTABLE8_REGISTER	 0x188   //nXTable8_REGISTER
#define	NXTABLE9_REGISTER	 0x189   //nXTable9_REGISTER
#define	NXTABLE10_REGISTER	 0x18A   //nXTable10_REGISTER
#define	NXTABLE11_REGISTER	 0x18B   //nXTable11_REGISTER
#define	NUSER18C_REGISTER	 0x18C   //nUser18C_REGISTER
#define	NUSER18D_REGISTER	 0x18D   //nUser18D_REGISTER
#define	NODSCTH_REGISTER	 0x18E   //nODSCTh_REGISTER
#define	NODSCCFG_REGISTER	 0x18F   //nODSCCfg_REGISTER
#define	NOCVTABLE0_REGISTER	 0x190   //nOCVTable0_REGISTER
#define	NOCVTABLE1_REGISTER	 0x191   //nOCVTable1_REGISTER
#define	NOCVTABLE2_REGISTER	 0x192   //nOCVTable2_REGISTER
#define	NOCVTABLE3_REGISTER	 0x193   //nOCVTable3_REGISTER
#define	NOCVTABLE4_REGISTER	 0x194   //nOCVTable4_REGISTER
#define	NOCVTABLE5_REGISTER	 0x195   //nOCVTable5_REGISTER
#define	NOCVTABLE6_REGISTER	 0x196   //nOCVTable6_REGISTER
#define	NOCVTABLE7_REGISTER	 0x197   //nOCVTable7_REGISTER
#define	NOCVTABLE8_REGISTER	 0x198   //nOCVTable8_REGISTER
#define	NOCVTABLE9_REGISTER	 0x199   //nOCVTable9_REGISTER
#define	NOCVTABLE10_REGISTER	 0x19A   //nOCVTable10_REGISTER
#define	NOCVTABLE11_REGISTER	 0x19B   //nOCVTable11_REGISTER
#define	NICHGTERM_REGISTER	 0x19C   //nIChgTerm_REGISTER
#define	NFILTERCFG_REGISTER	 0x19D   //nFilterCfg_REGISTER
#define	NVEMPTY_REGISTER	 0x19E   //nVEmpty_REGISTER
#define	NLEARNCFG_REGISTER	 0x19F   //nLearnCfg_REGISTER
#define	NQRTABLE00_REGISTER	 0x1A0   //nQRTable00_REGISTER
#define	NQRTABLE10_REGISTER	 0x1A1   //nQRTable10_REGISTER
#define	NQRTABLE20_REGISTER	 0x1A2   //nQRTable20_REGISTER
#define	NQRTABLE30_REGISTER	 0x1A3   //nQRTable30_REGISTER
#define	NCYCLES_REGISTER	 0x1A4   //nCycles_REGISTER
#define	NFULLCAPNOM_REGISTER	 0x1A5   //nFullCapNom_REGISTER
#define	NRCOMP0_REGISTER	 0x1A6   //nRComp0_REGISTER
#define	NTEMPCO_REGISTER	 0x1A7   //nTempCo_REGISTER
#define	NIAVGEMPTY_REGISTER	 0x1A8   //nIAvgEmpty_REGISTER
#define	NFULLCAPREP_REGISTER	 0x1A9   //nFullCapRep_REGISTER
#define	NVOLTTEMP_REGISTER	 0x1AA   //nVoltTemp_REGISTER
#define	NMAXMINCURR_REGISTER	 0x1AB   //nMaxMinCurr_REGISTER
#define	NMAXMINVOLT_REGISTER	 0x1AC   //nMaxMinVolt_REGISTER
#define	NMAXMINTEMP_REGISTER	 0x1AD   //nMaxMinTemp_REGISTER
#define	NSOC_REGISTER		 0x1AE   //nSOC_REGISTER
#define	NTIMERH_REGISTER	 0x1AF   //nTimerH_REGISTER
#define	NCONFIG_REGISTER	 0x1B0   //nConfig_REGISTER
#define	NRIPPLECFG_REGISTER	 0x1B1   //nRippleCfg_REGISTER
#define	NMISCCFG_REGISTER	 0x1B2   //nMiscCfg_REGISTER
#define	NDESIGNCAP_REGISTER	 0x1B3   //nDesignCap_REGISTER
#define	NHIBCFG_REGISTER	 0x1B4   //nHibCfg_REGISTER
#define	NPACKCFG_REGISTER	 0x1B5   //nPackCfg_REGISTER
#define	NRELAXCFG_REGISTER	 0x1B6   //nRelaxCfg_REGISTER
#define	NCONVGCFG_REGISTER	 0x1B7   //nConvgCfg_REGISTER
#define	NNVCFG0_REGISTER	 0x1B8   //nNVCfg0_REGISTER
#define	NNVCFG1_REGISTER	 0x1B9   //nNVCfg1_REGISTER
#define	NNVCFG2_REGISTER	 0x1BA   //nNVCfg2_REGISTER
#define	NSBSCFG_REGISTER	 0x1BB   //nSBSCfg_REGISTER
#define	NROMID0_REGISTER	 0x1BC   //nROMID0_REGISTER
#define	NROMID1_REGISTER	 0x1BD   //nROMID1_REGISTER
#define	NROMID2_REGISTER	 0x1BE   //nROMID2_REGISTER
#define	NROMID3_REGISTER	 0x1BF   //nROMID3_REGISTER
#define	NVALRTTH_REGISTER	 0x1C0   //nVAlrtTh_REGISTER
#define	NTALRTTH_REGISTER	 0x1C1   //nTAlrtTh_REGISTER
#define	NSALRTTH_REGISTER	 0x1C2   //nSAlrtTh_REGISTER
#define	NIALRTTH_REGISTER	 0x1C3   //nIAlrtTh_REGISTER
#define	NUSER1C4_REGISTER	 0x1C4   //nUser1C4_REGISTER
#define	NUSER1C5_REGISTER	 0x1C5   //nUser1C5_REGISTER
#define	NFULLSOCTHR_REGISTER	 0x1C6   //nFullSOCThr_REGISTER
#define	NTTFCFG_REGISTER	 0x1C7   //nTTFCfg_REGISTER
#define	NCGAIN_REGISTER		 0x1C8   //nCGain_REGISTER
#define	NTCURVE_REGISTER	 0x1C9   //nTCurve_REGISTER
#define	NTGAIN_REGISTER		 0x1CA   //nTGain_REGISTER
#define	NTOFF_REGISTER		 0x1CB   //nTOff_REGISTER
#define	NMANFCTRNAME0_REGISTER	 0x1CC   //nManfctrName0_REGISTER
#define	NMANFCTRNAME1_REGISTER	 0x1CD   //nManfctrName1_REGISTER
#define	NMANFCTRNAME2_REGISTER	 0x1CE   //nManfctrName2_REGISTER
#define	NRSENSE_REGISTER	 0x1CF   //nRSense_REGISTER
#define	NUSER1D0_REGISTER	 0x1D0   //nUser1D0_REGISTER
#define	NUSER1D1_REGISTER	 0x1D1   //nUser1D1_REGISTER
#define	NAGEFCCFG_REGISTER	 0x1D2   //nAgeFcCfg_REGISTER
#define	NDESIGNVOLTAGE_REGISTER	 0x1D3   //nDesignVoltage_REGISTER
#define	NUSER1D4_REGISTER	 0x1D4   //nUser1D4_REGISTER
#define	NRFASTVSHDN_REGISTER	 0x1D5   //nRFastVShdn_REGISTER
#define	NMANFCTRDATE_REGISTER	 0x1D6   //nManfctrDate_REGISTER
#define	NFIRSTUSED_REGISTER	 0x1D7   //nFirstUsed_REGISTER
#define	NSERIALNUMBER0_REGISTER	 0x1D8   //nSerialNumber0_REGISTER
#define	NSERIALNUMBER1_REGISTER	 0x1D9   //nSerialNumber1_REGISTER
#define	NSERIALNUMBER2_REGISTER	 0x1DA   //nSerialNumber2_REGISTER
#define	NDEVICENAME0_REGISTER	 0x1DB   //nDeviceName0_REGISTER
#define	NDEVICENAME1_REGISTER	 0x1DC   //nDeviceName1_REGISTER
#define	NDEVICENAME2_REGISTER	 0x1DD   //nDeviceName2_REGISTER
#define	NDEVICENAME3_REGISTER	 0x1DE   //nDeviceName3_REGISTER
#define	NDEVICENAME4_REGISTER	 0x1DF   //nDeviceName4_REGISTER

/* MAX17205 Data */
#define	NXTABLE0_DATA		 0x0000      //nXTable0_DATA
#define	NXTABLE1_DATA		 0x0000      //nXTable1_DATA
#define	NXTABLE2_DATA		 0x0000      //nXTable2_DATA
#define	NXTABLE3_DATA		 0x0000      //nXTable3_DATA
#define	NXTABLE4_DATA		 0x0000      //nXTable4_DATA
#define	NXTABLE5_DATA		 0x0000      //nXTable5_DATA
#define	NXTABLE6_DATA		 0x0000      //nXTable6_DATA
#define	NXTABLE7_DATA		 0x0000      //nXTable7_DATA
#define	NXTABLE8_DATA		 0x0000      //nXTable8_DATA
#define	NXTABLE9_DATA		 0x0000      //nXTable9_DATA
#define	NXTABLE10_DATA		 0x0000      //nXTable10_DATA
#define	NXTABLE11_DATA		 0x0000      //nXTable11_DATA
#define	NUSER18C_DATA		 0x0000      //nUser18C_DATA
#define	NUSER18D_DATA		 0x0000      //nUser18D_DATA
#define	NODSCTH_DATA		 0x0000      //nODSCTh_DATA
#define	NODSCCFG_DATA		 0x0000      //nODSCCfg_DATA
#define	NOCVTABLE0_DATA		 0x0000      //nOCVTable0_DATA
#define	NOCVTABLE1_DATA		 0x0000      //nOCVTable1_DATA
#define	NOCVTABLE2_DATA		 0x0000      //nOCVTable2_DATA
#define	NOCVTABLE3_DATA		 0x0000      //nOCVTable3_DATA
#define	NOCVTABLE4_DATA		 0x0000      //nOCVTable4_DATA
#define	NOCVTABLE5_DATA		 0x0000      //nOCVTable5_DATA
#define	NOCVTABLE6_DATA		 0x0000      //nOCVTable6_DATA
#define	NOCVTABLE7_DATA		 0x0000      //nOCVTable7_DATA
#define	NOCVTABLE8_DATA		 0x0000      //nOCVTable8_DATA
#define	NOCVTABLE9_DATA		 0x0000      //nOCVTable9_DATA
#define	NOCVTABLE10_DATA	 0x0000      //nOCVTable10_DATA
#define	NOCVTABLE11_DATA	 0x0000      //nOCVTable11_DATA
#define	NICHGTERM_DATA		 0x0000      //nIChgTerm_DATA
#define	NFILTERCFG_DATA		 0x0000      //nFilterCfg_DATA
#define	NVEMPTY_DATA		 0x0000      //nVEmpty_DATA
#define	NLEARNCFG_DATA		 0x2602      //nLearnCfg_DATA
#define	NQRTABLE00_DATA		 0x3C00      //nQRTable00_DATA
#define	NQRTABLE10_DATA		 0x1B80      //nQRTable10_DATA
#define	NQRTABLE20_DATA		 0x0B04      //nQRTable20_DATA
#define	NQRTABLE30_DATA		 0x0885      //nQRTable30_DATA
#define	NCYCLES_DATA		 0x0000      //nCycles_DATA
#define	NFULLCAPNOM_DATA	 0x0190      //nFullCapNom_DATA
#define	NRCOMP0_DATA		 0x1070      //nRComp0_DATA
#define	NTEMPCO_DATA		 0x263D      //nTempCo_DATA
#define	NIAVGEMPTY_DATA		 0xF830      //nIAvgEmpty_DATA
#define	NFULLCAPREP_DATA	 0x0190      //nFullCapRep_DATA
#define	NVOLTTEMP_DATA		 0x0000      //nVoltTemp_DATA
#define	NMAXMINCURR_DATA	 0x807F      //nMaxMinCurr_DATA
#define	NMAXMINVOLT_DATA	 0x00FF      //nMaxMinVolt_DATA
#define	NMAXMINTEMP_DATA	 0x807F      //nMaxMinTemp_DATA
#define	NSOC_DATA	         0x0000      //nSOC_DATA
#define	NTIMERH_DATA		 0x0000      //nTimerH_DATA
#define	NCONFIG_DATA		 0x0000      //nConfig_DATA
#define	NRIPPLECFG_DATA		 0x0204      //nRippleCfg_DATA
#define	NMISCCFG_DATA		 0x0000      //nMiscCfg_DATA
#define	NDESIGNCAP_DATA		 0x0190      //nDesignCap_DATA
#define	NHIBCFG_DATA		 0x0000      //nHibCfg_DATA
#define	NPACKCFG_DATA		 0x0E83      //nPackCfg_DATA
#define	NRELAXCFG_DATA		 0x0000      //nRelaxCfg_DATA
#define	NCONVGCFG_DATA		 0x2241      //nConvgCfg_DATA
#define	NNVCFG0_DATA		 0x0100      //nNVCfg0_DATA
#define	NNVCFG1_DATA		 0x0006      //nNVCfg1_DATA
#define	NNVCFG2_DATA		 0xFF0A      //nNVCfg2_DATA
#define	NSBSCFG_DATA		 0x0002      //nSBSCfg_DATA
#define	NROMID0_DATA		 0xFE26      //nROMID0_DATA
#define	NROMID1_DATA		 0x008F      //nROMID1_DATA
#define	NROMID2_DATA		 0x0020      //nROMID2_DATA
#define	NROMID3_DATA		 0x3000      //nROMID3_DATA
#define	NVALRTTH_DATA		 0x0000      //nVAlrtTh_DATA
#define	NTALRTTH_DATA		 0x0000      //nTAlrtTh_DATA
#define	NSALRTTH_DATA		 0x0000      //nSAlrtTh_DATA
#define	NIALRTTH_DATA		 0x0000      //nIAlrtTh_DATA
#define	NUSER1C4_DATA		 0x0000      //nUser1C4_DATA
#define	NUSER1C5_DATA		 0x0000      //nUser1C5_DATA
#define	NFULLSOCTHR_DATA	 0x0000      //nFullSOCThr_DATA
#define	NTTFCFG_DATA		 0x0000      //nTTFCfg_DATA
#define	NCGAIN_DATA		 0x0000      //nCGain_DATA
#define	NTCURVE_DATA		 0x0025      //nTCurve_DATA
#define	NTGAIN_DATA		 0x0000      //nTGain_DATA
#define	NTOFF_DATA		 0x0000      //nTOff_DATA
#define	NMANFCTRNAME0_DATA	 0x0000      //nManfctrName0_DATA
#define	NMANFCTRNAME1_DATA	 0x0000      //nManfctrName1_DATA
#define	NMANFCTRNAME2_DATA	 0x0000      //nManfctrName2_DATA
#define	NRSENSE_DATA		 0x00c8      //nRSense_DATA
#define	NUSER1D0_DATA		 0x0000      //nUser1D0_DATA
#define	NUSER1D1_DATA		 0x0000      //nUser1D1_DATA
#define	NAGEFCCFG_DATA		 0xD5E3      //nAgeFcCfg_DATA
#define	NDESIGNVOLTAGE_DATA	 0x0000      //nDesignVoltage_DATA
#define	NUSER1D4_DATA		 0x0000      //nUser1D4_DATA
#define	NRFASTVSHDN_DATA	 0x0000      //nRFastVShdn_DATA
#define	NMANFCTRDATE_DATA	 0x0000      //nManfctrDate_DATA
#define	NFIRSTUSED_DATA		 0x0000      //nFirstUsed_DATA
#define	NSERIALNUMBER0_DATA	 0x0000      //nSerialNumber0_DATA
#define	NSERIALNUMBER1_DATA	 0x0000      //nSerialNumber1_DATA
#define	NSERIALNUMBER2_DATA	 0x0000      //nSerialNumber2_DATA
#define	NDEVICENAME0_DATA	 0x0000      //nDeviceName0_DATA
#define	NDEVICENAME1_DATA	 0x0000      //nDeviceName1_DATA
#define	NDEVICENAME2_DATA	 0x0000      //nDeviceName2_DATA
#define	NDEVICENAME3_DATA	 0x0000      //nDeviceName3_DATA
#define	NDEVICENAME4_DATA	 0x0000      //nDeviceName4_DATA

/* Register Array */
uint16_t register_address[96] = {
        NXTABLE0_REGISTER,
        NXTABLE1_REGISTER,
        NXTABLE2_REGISTER,
        NXTABLE3_REGISTER,
        NXTABLE4_REGISTER,
        NXTABLE5_REGISTER,
        NXTABLE6_REGISTER,
        NXTABLE7_REGISTER,
        NXTABLE8_REGISTER,
        NXTABLE9_REGISTER,
        NXTABLE10_REGISTER,
        NXTABLE11_REGISTER,
        NUSER18C_REGISTER,
        NUSER18D_REGISTER,
        NODSCTH_REGISTER,
        NODSCCFG_REGISTER,
        NOCVTABLE0_REGISTER,
        NOCVTABLE1_REGISTER,
        NOCVTABLE2_REGISTER,
        NOCVTABLE3_REGISTER,
        NOCVTABLE4_REGISTER,
        NOCVTABLE5_REGISTER,
        NOCVTABLE6_REGISTER,
        NOCVTABLE7_REGISTER,
        NOCVTABLE8_REGISTER,
        NOCVTABLE9_REGISTER,
        NOCVTABLE10_REGISTER,
        NOCVTABLE11_REGISTER,
        NICHGTERM_REGISTER,
        NFILTERCFG_REGISTER,
        NVEMPTY_REGISTER,
        NLEARNCFG_REGISTER,
        NQRTABLE00_REGISTER,
        NQRTABLE10_REGISTER,
        NQRTABLE20_REGISTER,
        NQRTABLE30_REGISTER,
        NCYCLES_REGISTER,
        NFULLCAPNOM_REGISTER,
        NRCOMP0_REGISTER,
        NTEMPCO_REGISTER,
        NIAVGEMPTY_REGISTER,
        NFULLCAPREP_REGISTER,
        NVOLTTEMP_REGISTER,
        NMAXMINCURR_REGISTER,
        NMAXMINVOLT_REGISTER,
        NMAXMINTEMP_REGISTER,
        NSOC_REGISTER,
        NTIMERH_REGISTER,
        NCONFIG_REGISTER,
        NRIPPLECFG_REGISTER,
        NMISCCFG_REGISTER,
        NDESIGNCAP_REGISTER,
        NHIBCFG_REGISTER,
        NPACKCFG_REGISTER,
        NRELAXCFG_REGISTER,
        NCONVGCFG_REGISTER,
        NNVCFG0_REGISTER,
        NNVCFG1_REGISTER,
        NNVCFG2_REGISTER,
        NSBSCFG_REGISTER,
        NROMID0_REGISTER,
        NROMID1_REGISTER,
        NROMID2_REGISTER,
        NROMID3_REGISTER,
        NVALRTTH_REGISTER,
        NTALRTTH_REGISTER,
        NSALRTTH_REGISTER,
        NIALRTTH_REGISTER,
        NUSER1C4_REGISTER,
        NUSER1C5_REGISTER,
        NFULLSOCTHR_REGISTER,
        NTTFCFG_REGISTER,
        NCGAIN_REGISTER,
        NTCURVE_REGISTER,
        NTGAIN_REGISTER,
        NTOFF_REGISTER,
        NMANFCTRNAME0_REGISTER,
        NMANFCTRNAME1_REGISTER,
        NMANFCTRNAME2_REGISTER,
        NRSENSE_REGISTER,
        NUSER1D0_REGISTER,
        NUSER1D1_REGISTER,
        NAGEFCCFG_REGISTER,
        NDESIGNVOLTAGE_REGISTER,
        NUSER1D4_REGISTER,
        NRFASTVSHDN_REGISTER,
        NMANFCTRDATE_REGISTER,
        NFIRSTUSED_REGISTER,
        NSERIALNUMBER0_REGISTER,
        NSERIALNUMBER1_REGISTER,
        NSERIALNUMBER2_REGISTER,
        NDEVICENAME0_REGISTER,
        NDEVICENAME1_REGISTER,
        NDEVICENAME2_REGISTER,
        NDEVICENAME3_REGISTER,
        NDEVICENAME4_REGISTER
};

/* Data array */
uint16_t register_data[96] = {
        NXTABLE0_DATA,
        NXTABLE1_DATA,
        NXTABLE2_DATA,
        NXTABLE3_DATA,
        NXTABLE4_DATA,
        NXTABLE5_DATA,
        NXTABLE6_DATA,
        NXTABLE7_DATA,
        NXTABLE8_DATA,
        NXTABLE9_DATA,
        NXTABLE10_DATA,
        NXTABLE11_DATA,
        NUSER18C_DATA,
        NUSER18D_DATA,
        NODSCTH_DATA,
        NODSCCFG_DATA,
        NOCVTABLE0_DATA,
        NOCVTABLE1_DATA,
        NOCVTABLE2_DATA,
        NOCVTABLE3_DATA,
        NOCVTABLE4_DATA,
        NOCVTABLE5_DATA,
        NOCVTABLE6_DATA,
        NOCVTABLE7_DATA,
        NOCVTABLE8_DATA,
        NOCVTABLE9_DATA,
        NOCVTABLE10_DATA,
        NOCVTABLE11_DATA,
        NICHGTERM_DATA,
        NFILTERCFG_DATA,
        NVEMPTY_DATA,
        NLEARNCFG_DATA,
        NQRTABLE00_DATA,
        NQRTABLE10_DATA,
        NQRTABLE20_DATA,
        NQRTABLE30_DATA,
        NCYCLES_DATA,
        NFULLCAPNOM_DATA,
        NRCOMP0_DATA,
        NTEMPCO_DATA,
        NIAVGEMPTY_DATA,
        NFULLCAPREP_DATA,
        NVOLTTEMP_DATA,
        NMAXMINCURR_DATA,
        NMAXMINVOLT_DATA,
        NMAXMINTEMP_DATA,
        NSOC_DATA,
        NTIMERH_DATA,
        NCONFIG_DATA,
        NRIPPLECFG_DATA,
        NMISCCFG_DATA,
        NDESIGNCAP_DATA,
        NHIBCFG_DATA,
        NPACKCFG_DATA,
        NRELAXCFG_DATA,
        NCONVGCFG_DATA,
        NNVCFG0_DATA,
        NNVCFG1_DATA,
        NNVCFG2_DATA,
        NSBSCFG_DATA,
        NROMID0_DATA,
        NROMID1_DATA,
        NROMID2_DATA,
        NROMID3_DATA,
        NVALRTTH_DATA,
        NTALRTTH_DATA,
        NSALRTTH_DATA,
        NIALRTTH_DATA,
        NUSER1C4_DATA,
        NUSER1C5_DATA,
        NFULLSOCTHR_DATA,
        NTTFCFG_DATA,
        NCGAIN_DATA,
        NTCURVE_DATA,
        NTGAIN_DATA,
        NTOFF_DATA,
        NMANFCTRNAME0_DATA,
        NMANFCTRNAME1_DATA,
        NMANFCTRNAME2_DATA,
        NRSENSE_DATA,
        NUSER1D0_DATA,
        NUSER1D1_DATA,
        NAGEFCCFG_DATA,
        NDESIGNVOLTAGE_DATA,
        NUSER1D4_DATA,
        NRFASTVSHDN_DATA,
        NMANFCTRDATE_DATA,
        NFIRSTUSED_DATA,
        NSERIALNUMBER0_DATA,
        NSERIALNUMBER1_DATA,
        NSERIALNUMBER2_DATA,
        NDEVICENAME0_DATA,
        NDEVICENAME1_DATA,
        NDEVICENAME2_DATA,
        NDEVICENAME3_DATA,
        NDEVICENAME4_DATA
};

#endif //PX4_CHARGING_I2C_H


